# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-13 15:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Upload', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='normaluser',
            name='headImg',
            field=models.FileField(upload_to='F:\\github\\WBFL\\TianWen\\media\\upload', verbose_name='文件'),
        ),
    ]
